# => This Stupid code was generated by chatGTP, thanks :)

import pygame
import os
os.environ["SDL_VIDEODRIVER"] = "dummy"

pygame.init()

BLACK = (0, 0, 0)
WHITE = (255, 255, 255)

size = (700, 500)
screen = pygame.display.set_mode(size)
pygame.display.set_caption("Snake")
clock = pygame.time.Clock()

x = 350
y = 250
dx = 0
dy = 0

snake = [pygame.Rect(x, y, 10, 10)]

done = False
while not done:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            done = True
        elif event.type == pygame.KEYDOWN:
            if event.key == pygame.K_LEFT:
                dx = -10
                dy = 0
            elif event.key == pygame.K_RIGHT:
                dx = 10
                dy = 0
            elif event.key == pygame.K_UP:
                dx = 0
                dy = -10
            elif event.key == pygame.K_DOWN:
                dx = 0
                dy = 10

    x += dx
    y += dy
    snake.insert(0, pygame.Rect(x, y, 10, 10))
    snake.pop()

    screen.fill(BLACK)

    for rect in snake:
        pygame.draw.rect(screen, WHITE, rect)

    pygame.display.flip()

    clock.tick(10)

pygame.quit()
